FROM node:lts AS builder
WORKDIR /home/app
COPY yarn.lock yarn.lock
COPY package.json package.json
COPY .yarn/cache .yarn/cache/
COPY .yarn/releases .yarn/releases/
COPY .yarn/plugins .yarn/plugins/
COPY .yarnrc.yml .yarnrc.yml
RUN yarn
COPY .eslintrc.js .eslintrc.js
COPY .prettierrc .prettierrc
COPY nest-cli.json nest-cli.json
COPY tsconfig.build.json tsconfig.build.json
COPY tsconfig.json tsconfig.json
COPY src src
CMD ["yarn", "start:dev"]

FROM builder AS final
WORKDIR /home/app
RUN yarn build
CMD ["yarn", "start:prod"]
