export const serviceWorkerEvents = {
    UPDATE_SERVICE_WORKER: 'UPDATE_SERVICE_WORKER',
    INITIALIZE_CONTENT_SCRIPT_DATA: 'INITIALIZE_CONTENT_SCRIPT_DATA',
    INITIALIZE_POP_UP_DATA: 'INITIALIZE_POP_UP_DATA',
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
};

export type IServiceWorkerEvents = typeof serviceWorkerEvents;
